### ISSUE TITLE
make node text not overlap 

### ISSUE THREAD

**Issue by tmad4000** [willzeng/WikiNets#43] opened 2014-01-19 06:16 UTC
See 
http://stackoverflow.com/questions/12944024/d3-js-how-can-i-prevent-circles-text-overlapping
and 
http://bl.ocks.org/MoritzStefaner/1377729

**Comment by willzeng** [comment] 2014-01-19 10:18
This is a duplicate of https://github.com/willzeng/WikiNets/issues/15

**Closed as completed by willzeng** 2014-01-19 10:18 UTC
