### ISSUE TITLE
make graph view, list view tabs

### ISSUE THREAD

**Issue by tmad4000** [willzeng/WikiNets#49] opened 2014-01-19 06:23 UTC
even if we have nothing to populate list view with yet, it'll get our heads in order

**Comment by willzeng** [comment] 2014-01-19 10:23
This will be done when we have an interface wireframe mocked up.

Also, this is a duplicate of:
https://github.com/willzeng/WikiNets/issues/12

**Comment by willzeng** [comment] 2014-02-03 22:00
I'm basically reopening this just to close it with the new commit.

**Comment by willzeng** [comment] 2014-02-03 22:00
Closed with the first implementation at:
https://github.com/willzeng/WikiNets/commit/55beca8e4080b4cd491cb21bbeb53957f1b4b3dc

@tmad4000

**Closed as completed by willzeng** 2014-02-03 22:00 UTC
